-- AlterTable
ALTER TABLE `TimeEntry`
  ADD COLUMN `totalPausedSeconds` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `pausedAt` DATETIME(3) NULL,
  ADD COLUMN `status` ENUM('RUNNING', 'PAUSED', 'COMPLETED') NOT NULL DEFAULT 'RUNNING';

UPDATE `TimeEntry`
SET `status` = CASE
  WHEN `endTime` IS NULL THEN 'RUNNING'
  ELSE 'COMPLETED'
END;

-- AlterTable
ALTER TABLE `TaskActivity`
  MODIFY `action` ENUM(
    'TASK_CREATED',
    'TASK_UPDATED',
    'TASK_STATUS_CHANGED',
    'TASK_DESCRIPTION_UPDATED',
    'TASK_ASSIGNED',
    'TASK_UNASSIGNED',
    'ATTACHMENT_UPLOADED',
    'ATTACHMENT_DELETED',
    'COMMENT_ADDED',
    'COMMENT_EDITED',
    'COMMENT_DELETED',
    'COMMENT_REPLIED',
    'TIMER_PAUSED',
    'TIMER_RESUMED',
    'TIMER_STOPPED'
  ) NOT NULL;
